-- MySQL Script generated by MySQL Workbench
-- Tue Sep 13 11:01:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema undergrounds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema undergrounds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `undergrounds` DEFAULT CHARACTER SET utf8 ;
USE `undergrounds` ;

-- -----------------------------------------------------
-- Table `undergrounds`.`depots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`depots` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`depots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`lines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`lines` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `depot_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_lines_depots1_idx` (`depot_id` ASC) VISIBLE,
  UNIQUE INDEX `depot_id_UNIQUE` (`depot_id` ASC) VISIBLE,
  CONSTRAINT `fk_lines_depots1`
    FOREIGN KEY (`depot_id`)
    REFERENCES `undergrounds`.`depots` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`stations` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`stations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`ticket_boxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`ticket_boxes` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`ticket_boxes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_boxes_stations1_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_boxes_stations1`
    FOREIGN KEY (`station_id`)
    REFERENCES `undergrounds`.`stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`cashiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`cashiers` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`cashiers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dob` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`turnstiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`turnstiles` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`turnstiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turnstiles_stations1_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_turnstiles_stations1`
    FOREIGN KEY (`station_id`)
    REFERENCES `undergrounds`.`stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`platforms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`platforms` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`platforms` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_platforms_stations1_idx` (`station_id` ASC) VISIBLE,
  CONSTRAINT `fk_platforms_stations1`
    FOREIGN KEY (`station_id`)
    REFERENCES `undergrounds`.`stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`signs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`signs` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`signs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `platform_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_signs_platforms1_idx` (`platform_id` ASC) VISIBLE,
  CONSTRAINT `fk_signs_platforms1`
    FOREIGN KEY (`platform_id`)
    REFERENCES `undergrounds`.`platforms` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`trains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`trains` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`trains` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `depot_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trains_depots1_idx` (`depot_id` ASC) VISIBLE,
  CONSTRAINT `fk_trains_depots1`
    FOREIGN KEY (`depot_id`)
    REFERENCES `undergrounds`.`depots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`carriages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`carriages` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`carriages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `train_id` BIGINT UNSIGNED NOT NULL,
  `seat_capacity` INT NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `carriage_number` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carriages_trains1_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `fk_carriages_trains1`
    FOREIGN KEY (`train_id`)
    REFERENCES `undergrounds`.`trains` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`drivers` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`drivers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dob` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`train_drivers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`train_drivers` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`train_drivers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `train_id` BIGINT UNSIGNED NOT NULL,
  `driver_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_trains_has_drivers_drivers1_idx` (`driver_id` ASC) VISIBLE,
  INDEX `fk_trains_has_drivers_trains_idx` (`train_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_trains_has_drivers_trains`
    FOREIGN KEY (`train_id`)
    REFERENCES `undergrounds`.`trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trains_has_drivers_drivers1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `undergrounds`.`drivers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`line_stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`line_stations` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`line_stations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `line_id` BIGINT UNSIGNED NOT NULL,
  `station_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_lines_has_stations_stations1_idx` (`station_id` ASC) VISIBLE,
  INDEX `fk_lines_has_stations_lines1_idx` (`line_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lines_has_stations_lines1`
    FOREIGN KEY (`line_id`)
    REFERENCES `undergrounds`.`lines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lines_has_stations_stations1`
    FOREIGN KEY (`station_id`)
    REFERENCES `undergrounds`.`stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `undergrounds`.`ticket_box_cashiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `undergrounds`.`ticket_box_cashiers` ;

CREATE TABLE IF NOT EXISTS `undergrounds`.`ticket_box_cashiers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_box_id` BIGINT UNSIGNED NOT NULL,
  `cashier_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_boxes_has_cashiers_cashiers1_idx` (`cashier_id` ASC) VISIBLE,
  INDEX `fk_ticket_boxes_has_cashiers_ticket_boxes1_idx` (`ticket_box_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_boxes_has_cashiers_ticket_boxes1`
    FOREIGN KEY (`ticket_box_id`)
    REFERENCES `undergrounds`.`ticket_boxes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_boxes_has_cashiers_cashiers1`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `undergrounds`.`cashiers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
